#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  jq -n --arg version "${YARN_VERSION}" '{private: true, devDependencies: { yarn: $version } }' > "$shome/package.json.$$"
  mv -f "$shome/package.json.$$" "$shome/package.json"
  block compile npm
  (set +f; cd "$shome/bin" && ln -nfs ../node_modules/.bin/yarn* .)
}

bootstrap
