#!/usr/bin/env bash

function _yarn_profile {
  local shome="${_yarn_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  if [[ ! -f "${DATA}/.slow_as_shit" ]]; then
    export YARN_CACHE_FOLDER="${DATA}/cache/yarn"
  fi
}

_yarn_profile
