#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_yarn="$(yarn --version 2>/dev/null || true)"
  jq -n \
    --arg yarn "$ver_yarn" \
    '{yarn: $yarn}'
}

version "$@"
